Debugger entered--Lisp error: (invalid-read-syntax "#")
  read(#<buffer *scratch*>)
  elisp--eval-defun()
  eval-defun(nil)
  funcall-interactively(eval-defun nil)
  call-interactively(eval-defun nil nil)
  command-execute(eval-defun)
